In [29]:
import pandas as pd
import numpy as np

In [30]:
data = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\Content Monetization Modeler\youtube_ad_revenue_dataset.csv")
print(data)

        video_id                        date  views   likes  comments  \
0       vid_3092  2024-09-24 10:50:40.993199   9936  1221.0     320.0
1       vid_3459  2024-09-22 10:50:40.993199  10017   642.0     346.0
2       vid_4784  2024-11-21 10:50:40.993199  10097  1979.0     187.0
3       vid_4078  2025-01-28 10:50:40.993199  10034  1191.0     242.0
4       vid_3522  2025-04-28 10:50:40.993199   9889  1858.0     477.0
...          ...                         ...    ...     ...       ...
122395  vid_2902  2024-12-14 10:50:40.993199   9853  1673.0     147.0
122396  vid_3890  2024-07-13 10:50:40.993199  10128  1709.0      63.0
122397  vid_3934  2024-06-10 10:50:40.993199  10267   700.0       NaN
122398  vid_4260  2024-12-22 10:50:40.993199  10240  1616.0     106.0
122399  vid_1056  2024-06-25 10:50:40.993199   9931   770.0       NaN

        watch_time_minutes  video_length_minutes  subscribers       category  \
0             26497.214184              2.862137       228086  Entertainment
1             15209.747445             23.738069       736015         Gaming
2             57332.658498             26.200634       240534      Education
3             31334.517771             11.770340       434482  Entertainment
4             15665.666434              6.635854        42030      Education
...                    ...                   ...          ...            ...
122395        42075.704885             25.490195       210818      Education
122396        57563.703040             16.229133       878860          Music
122397        27549.714659             23.822365       576756           Tech
122398        56967.384382              7.753099       585138          Music
122399        38466.837135             27.305703       517587           Tech

         device country  ad_revenue_usd
0            TV      IN      203.178237
1        Tablet      CA      140.880508
2            TV      CA      360.134008
3        Mobile      UK      224.638261
4        Mobile      CA      165.514388
...         ...     ...             ...
122395   Tablet      US      280.986396
122396  Desktop      UK      354.612981
122397   Tablet      CA      203.643106
122398   Mobile      UK      351.525811
122399       TV      CA      253.842824

[122400 rows x 12 columns]

In [31]:
data.shape

(122400, 12)

In [32]:
data.columns

Index(['video_id', 'date', 'views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd'],
      dtype='object')

In [33]:
data.dtypes

video_id                 object
date                     object
views                     int64
likes                   float64
comments                float64
watch_time_minutes      float64
video_length_minutes    float64
subscribers               int64
category                 object
device                   object
country                  object
ad_revenue_usd          float64
dtype: object

In [34]:
data.isnull().sum()

video_id                   0
date                       0
views                      0
likes                   6117
comments                6112
watch_time_minutes      6105
video_length_minutes       0
subscribers                0
category                   0
device                     0
country                    0
ad_revenue_usd             0
dtype: int64

In [35]:
data.duplicated().sum()

np.int64(2400)

In [36]:
data.describe()

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd
count,122400.000000,116283.000000,116288.000000,116295.000000,122400.000000,122400.000000,122400.000000
mean,9999.856283,1099.633618,274.396636,37543.827721,16.014165,502191.719902,252.727210
std,99.881260,519.424089,129.741739,12987.724246,8.083790,288397.470103,61.957052
min,9521.000000,195.000000,48.000000,14659.105562,2.000142,1005.000000,126.590603
25%,9933.000000,650.000000,162.000000,26366.320569,9.004695,252507.500000,199.902018
50%,10000.000000,1103.000000,274.000000,37531.990337,16.005906,503465.500000,252.749699
75%,10067.000000,1547.000000,387.000000,48777.782090,23.021260,752192.000000,305.597518
max,10468.000000,2061.000000,515.000000,61557.670089,29.999799,999997.000000,382.768254

In [37]:
data["video_id"].unique()

array(['vid_3092', 'vid_3459', 'vid_4784', ..., 'vid_4757', 'vid_3953',
       'vid_2224'], shape=(5000,), dtype=object)

In [38]:
data.nunique()

video_id                  5000
date                       365
views                      736
likes                     1855
comments                   466
watch_time_minutes      114000
video_length_minutes    120000
subscribers             113254
category                     6
device                       4
country                      6
ad_revenue_usd          120000
dtype: int64

In [39]:
data['category'].value_counts()

category
Education        20514
Music            20475
Tech             20444
Entertainment    20411
Gaming           20359
Lifestyle        20197
Name: count, dtype: int64

In [40]:
data['country'].value_counts()

country
CA    20603
DE    20582
IN    20564
AU    20313
UK    20269
US    20069
Name: count, dtype: int64

In [41]:
data['device'].value_counts()

device
TV         30646
Mobile     30598
Tablet     30579
Desktop    30577
Name: count, dtype: int64

In [42]:
(data.isnull().sum()/len(data))*100

video_id                0.000000
date                    0.000000
views                   0.000000
likes                   4.997549
comments                4.993464
watch_time_minutes      4.987745
video_length_minutes    0.000000
subscribers             0.000000
category                0.000000
device                  0.000000
country                 0.000000
ad_revenue_usd          0.000000
dtype: float64

In [43]:
data.dropna()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122392,vid_4304,2025-02-11 10:50:40.993199,10024,1701.0,194.0,44052.691192,4.342520,620651,Music,TV,US,292.486997
122394,vid_4483,2025-03-21 10:50:40.993199,9841,1638.0,323.0,26845.644869,4.992376,637259,Gaming,Desktop,UK,211.544626
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811

In [44]:
missing_percent = data.isnull().mean() * 100
cols_to_drop = missing_percent[missing_percent > 50].index
data = data.drop(columns=cols_to_drop)

In [45]:
# Mean imputation (for normally distributed data)
data['likes'] = data['likes'].fillna(data['likes'].mean())

# Median imputation (for skewed data)
data['comments'] = data['comments'].fillna(data['comments'].median())

# Mean imputation again
data['watch_time_minutes'] = data['watch_time_minutes'].fillna(data['watch_time_minutes'].mean())

In [46]:
# Detect numeric columns
num_cols = data.select_dtypes(include=['int64', 'float64']).columns

# Loop through numeric columns and impute
for col in num_cols:
    skewness = data[col].skew()
    if abs(skewness) < 0.5:
        data[col].fillna(data[col].mean(), inplace=True)
        print(f"{col}: Filled missing values with MEAN (normal distribution)")
    else:
        data[col].fillna(data[col].median(), inplace=True)
        print(f"{col}: Filled missing values with MEDIAN (skewed distribution)")

# Check if all missing values are filled
print("\n Missing values after imputation:\n")
print(data.isnull().sum())

views: Filled missing values with MEAN (normal distribution)
likes: Filled missing values with MEAN (normal distribution)
comments: Filled missing values with MEAN (normal distribution)
watch_time_minutes: Filled missing values with MEAN (normal distribution)
video_length_minutes: Filled missing values with MEAN (normal distribution)
subscribers: Filled missing values with MEAN (normal distribution)
ad_revenue_usd: Filled missing values with MEAN (normal distribution)

 Missing values after imputation:

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14176\1699045059.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

In [47]:
# Detect categorical columns
cat_cols = data.select_dtypes(include=['object']).columns

# Fill missing values with mode
for col in cat_cols:
    if data[col].isnull().sum() > 0:
        data[col].fillna(data[col].mode()[0], inplace=True)
        print(f"{col}: Filled missing values with MODE → '{data[col].mode()[0]}'")
    else:
        print(f"{col}: No missing values found.")

print("\n Missing values after categorical imputation:\n")
print(data.isnull().sum())

video_id: No missing values found.
date: No missing values found.
category: No missing values found.
device: No missing values found.
country: No missing values found.

 Missing values after categorical imputation:

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

In [48]:
# Forward Fill → fill missing values using the previous value
data_ffill = data.fillna(method='ffill')
print("Forward Fill applied - Missing values filled using previous row value.\n")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14176\3681005553.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_ffill = data.fillna(method='ffill')

Forward Fill applied - Missing values filled using previous row value.

In [49]:
# Backward Fill → fill missing values using the next value
data_bfill = data.fillna(method='bfill')
print("Backward Fill applied - Missing values filled using next row value.\n")

Backward Fill applied - Missing values filled using next row value.

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14176\1435794488.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_bfill = data.fillna(method='bfill')

In [50]:
print("Missing values after Forward Fill:\n", data_ffill.isnull().sum())
print("\nMissing values after Backward Fill:\n", data_bfill.isnull().sum())

Missing values after Forward Fill:
 video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

Missing values after Backward Fill:
 video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64

In [51]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
data_knn = pd.DataFrame(imputer.fit_transform(data.select_dtypes(include=['int64', 'float64'])),
                        columns=data.select_dtypes(include=['int64', 'float64']).columns)

print("KNN Imputation applied — Missing values predicted using nearest neighbor values.\n")
print("Missing values after KNN Imputation:\n", data_knn.isnull().sum())

KNN Imputation applied — Missing values predicted using nearest neighbor values.

Missing values after KNN Imputation:
 views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
ad_revenue_usd          0
dtype: int64

In [52]:
# Verify all missing values are handled
missing_check = data.isnull().sum()

print("Missing Values After Handling:\n")
print(missing_check)

Missing Values After Handling:

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
dtype: int64